### ISSUE TITLE
1.3 Stakeholder and user descriptions for sprint 1

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/SOEN390-Team05-W23#14]
The Stakeholder and user descriptions section of the sprint 1 report consists of the stakeholder summary, user summary, user environment

**Comment by AlpErdinc** [comment]
The google doc has been updated and all of 1.3 is finalized with UI team added to stakeholders. 
Now waiting for review.

**Comment by imran1289-ah** [comment]
Reviewed and everything looks good for me!!
