### ISSUE TITLE
1.6 Other product requirements for sprint 1

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/SOEN390-Team05-W23#17]
Section 1.6 for the sprint 1 report.

**Comment by imran1289-ah** [comment]
Some suggested comments from @Aboudik1452 

![Image](https://user-images.githubusercontent.com/77070862/214121629-ca24d880-7956-4bda-8960-32c069a6ddb2.png)

**Comment by Resident-png** [comment]
That is true, I have deleted it.
